groups:
  - name: example
    rules:
      - alert: InstanceDown
        expr: up == 0
        # for: 1m
        for: 20s
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 20 seconds."

      - alert: TLSExpiry4weeks
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7 * 4
        for: 5m
        labels: 
          severity: warning
        annotations:
          description: "TLS certificate will expire in {{ $value | humanizeDuration }}"
      
      - alert: TLSExpiry1week
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
        for: 5m
        labels: 
          severity: critical
        annotations:
          description: "TLS certificate will expire in {{ $value | humanizeDuration }}"
                    
  - name: demo-service-alerts
    rules:
      - alert: DemoServiceHighErrorRate
        expr: |
          (
            sum without(status, instance) (
              rate(http_server_request_duration_seconds_count{job="techstack",http_response_status_code=~"5.."}[1m])
            )
          /
            sum without(status, instance) (
              rate(http_server_request_duration_seconds_count{job="techstack"}[1m])
            ) * 100 > 0.5
          )
        # for: 1m
        for: 20s
        labels:
          severity: critical
          channel: discord
        annotations:
          title: "High 5xx rate for {{ $labels.method }} on {{ $labels.path }}"
          description: 'The 5xx error rate for path {{$labels.path}} with method {{ $labels.method }} in {{ $labels.job }} is {{ printf "%.2f" $value }}%.'
