groups:
  - name: example
    rules:
      - alert: InstanceDown
        expr: up == 0
        # for: 1m
        for: 20s
  - name: demo-service-alerts
    rules:
      - alert: DemoServiceHighErrorRate
        expr: |
          (
            sum without(status, instance) (
              rate(http_request_duration_seconds_count{status=~"5..",job="techstack"}[1m])
            )
          /
            sum without(status, instance) (
              rate(http_request_duration_seconds_count{job="techstack"}[1m])
            ) * 100 > 0.5
          )
        # for: 1m
        for: 20s
        labels:
          severity: critical
        annotations:
          title: "High 5xx rate for {{ $labels.method }} on {{ $labels.path }}"
          description: 'The 5xx error rate for path {{$labels.path}} with method {{ $labels.method }} in {{ $labels.job }} is {{ printf "%.2f" $value }}%.'
